title : "> Native Build"
description: "Blog sobre desenvolvimento de aplicativos para smartphones com JavaScript, HTML5 e CSS3"

encoding:    utf-8
safe:        false
port:        4000
baseurl:     /
url:         http://felquis.com
paginate:    4

source:      ./_source
destination: ./_site
plugins:     ./_source/_plugins

future:      true
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink:   /:year/:title.html